import { BaseModel } from '../../../shared-model/base.model';
import { Branch } from './branch.model';
export class BranchDailyMinimalCapacity extends BaseModel{
  harareStaticCbd: number;
  harareMob1: number;
  harareMob2: number;
  harareMob3: number;
  harareTotalMinCapacity: number;
  harareExpectedDailyCollections: number;
  hararePercentageCapacity: number;
  bulawayoStaticCbd: number;
  bulawayoMob1: number;
  bulawayoMob2: number;
  bulawayoMob3: number;
  bulawayoTotalMinCapacity: number;
  bulawayoExpectedDailyCollections: number;
  bulawayoPercentageCapacity: number;
  gweruStaticCbd: number;
  gweruMob1: number;
  gweruMob2: number;
  gweruMob3: number;
  gweruTotalMinCapacity: number;
  gweruExpectedDailyCollections: number;
  gweruPercentageCapacity: number;
  mutareStaticCbd: number;
  mutareMob1: number;
  mutareMob2: number;
  mutareMob3: number;
  mutareTotalMinCapacity: number;
  mutareExpectedDailyCollections: number;
  mutarePercentageCapacity: number;
  masvingoStaticCbd: number;
  masvingoMob1: number;
  masvingoMob2: number;
  masvingoMob3: number;
  masvingoTotalMinCapacity: number;
  masvingoExpectedDailyCollections: number;
  masvingoPercentageCapacity: number;
  totalStaticCbd: number;
  totalMob1: number;
  totalMob2: number;
  totalMob3: number;
  totalTotalMinCapacity: number;
  totalExDailyCollections: number;
  totalPercentageCapacity: number;
  fixedPercentage: number;
  mobPercentage: number;
}
